#!/bin/bash

function show_usage() {

    echo "usage: calendar [global arguments] ${1:-<command>} [command arguments]"
    echo ""

    command_prefix=""
    arg_prefix="  "
    if [ -z "$1" ]; then
        echo "commands:"
        command_prefix="  "
    fi
    if [ -z "$1" ] || [[ "$1" == "init" ]]; then
        echo -n "$command_prefix"
        echo "init" $'\t' $'\t' $'\t' $'\t' $'\t' "Initialize the calendar directory"
    fi
    if [ -z "$1" ] || [[ "$1" == "generate" ]]; then
        echo -n "$command_prefix"
        echo "generate" "[cmd args]" "<filename>" $'\t' "Generate a new calendar"
        echo -n "$command_prefix"
        echo -n "$arg_prefix"
        echo "-n|--name" $'\t' $'\t' $'\t' $'\t' "Specify name for calendar"
    fi
    if [ -z "$1" ] || [[ "$1" == "add_event" ]]; then
        echo -n "$command_prefix"
        echo "add_event" "[cmd args]" "<filename>" $'\t' "Generate a new calendar"
        echo -n "$command_prefix"
        echo -n "$arg_prefix"
        echo "-s|--summary" $'\t' $'\t' $'\t' "Specify name for calendar"
        echo -n "$command_prefix"
        echo -n "$arg_prefix"
        echo "-b|--begin" $'\t' $'\t' $'\t' $'\t' "Specify begin time for event"
        echo -n "$command_prefix"
        echo -n "$arg_prefix"
        echo "-e|--end" $'\t' $'\t' $'\t' $'\t' "Specify end time for event"
        echo -n "$command_prefix"
        echo -n "$arg_prefix"
        echo "-d|--description" $'\t' $'\t' $'\t' "Specify description for calendar event"
    fi
    if [ -z "$1" ] || [[ "$1" == "edit" ]]; then
        echo -n "$command_prefix"
        echo "edit" "<filename>" $'\t' $'\t' $'\t' "Edit raw calendar file"
    fi
    if [ -z "$1" ]; then
        echo -n "$command_prefix"
        echo "rm" "<filename>" $'\t' $'\t' $'\t' "Remove a file"
    fi
    if [ -z "$1" ]; then
        echo -n "$command_prefix"
        echo "ls" $'\t' $'\t' $'\t' $'\t' $'\t' "View directory structure"
    fi

    echo ""
    echo "global arguments:"
    echo -n "$arg_prefix"
    echo "-p|--path" $'\t' $'\t' $'\t' $'\t' "Set the calendar directory to work with"

}

function cmd_init() {

    while ! [[ "$1" == "" ]]; do
        case "$1" in
            "-h"|"--help")
                show_usage "init"
                exit
                ;;
            *)
                echo "Unknown init parameter $1"
                show_usage "init"
                exit 1
                ;;
        esac
        shift
    done

    if [ -d "$working_path" ]; then
        echo "Cannot init: Already initialized"
        exit 1
    fi

    mkdir "$working_path"
    echo "Calendar store initialized"
    exit 0
}

function cmd_generate() {

    while ! [[ "$1" == "" ]]; do
        case "$1" in
            "-n"|"--name")
                shift
                cal_name="$1"
                ;;
            "-h"|"--help")
                show_usage "generate"
                exit
                ;;
            *)
                if [ -z "$filename" ]; then
                    filename="$1"
                else
                    echo "Unknown generate parameter $1"
                    show_usage "generate"
                    exit 1
                fi
                ;;
        esac
        shift
    done

    if [ -z "$filename" ]; then
        echo "A file must be specified"
        show_usage "generate"
        exit 1
    fi

    if [ -e "$working_path/$filename" ]; then
        echo "Cannot generate: Already exists"
        exit 1
    fi

    if [ -z "${filename%\/*}" ]&& ! [ -e "$working_path/${filename%\/*}" ]; then
        mkdir -p "$working_path/${filename%\/*}"
        err="$?"
        if ! [[ "$err" == "0" ]]; then
            echo "Cannot make directory ${filename%\/*}"
            exit "$err"
        fi
    fi

    {
        echo "BEGIN:VCALENDAR"
        if ! [ -z "$cal_name" ]; then
            echo "NAME:$cal_name"
            echo "X-WR-CALNAME:$cal_name"
        fi
        echo "VERSION:2.0"
        echo "PRODID:-//MilesBreslin//ShellCal//EN"

        echo "END:VCALENDAR"
    } > "$working_path/$filename"

    err="$?"
    if ! [[ "$err" == "0" ]]; then
        echo "Cannot generate file"
        exit "$?"
    fi
}

function cmd_add_event() {
    while ! [[ "$1" == "" ]]; do
        case "$1" in
            "-s"|"--summary")
                shift
                event_summary="$1"
                ;;
            "-d"|"--description")
                shift
                event_description="$1"
                ;;
            "-b"|"--begin"|"--start")
                shift
                event_start="$(date --date="$1" --rfc-822)"
                ;;
            "-e"|"--end"|"--stop")
                shift
                event_stop="$(date --date="$1" --rfc-822)"
                ;;
            "-h"|"--help")
                show_usage "add_event"
                exit
                ;;
            *)
                if [ -z "$filename" ]; then
                    filename="$1"
                else
                    echo "Unknown add_event parameter $1"
                    show_usage "add_event"
                    exit 1
                fi
                ;;
        esac
        shift
    done

    if ! [ -e "$working_path/$filename" ]; then
        echo "Cannot create event: File does not exist"
        exit 1
    fi

    if [ -z "$event_start" ] || [ -z "$event_stop" ]; then
        echo "Cannot create event: Must have begin and end times"
        exit 1
    fi

    {
        echo "BEGIN:VEVENT"
        echo "CREATED:$(date -u '+%Y%m%dT%H%M%SZ')"
        echo "UID:ShellCal_$RANDOM"
        if ! [ -z "$event_summary" ]; then
            echo "SUMMARY:$event_summary"
        fi
        if ! [ -z "$event_description" ]; then
            echo "DESCRIPTION:$event_description"
        fi
        echo "DTSTART:$(date --date="$event_start" -u '+%Y%m%dT%H%M%SZ')"
        echo "DTEND:$(date --date="$event_stop" -u '+%Y%m%dT%H%M%SZ')"
        echo "END:VEVENT"
    } | append_to_calendar "$working_path/$filename" 
    exit "$?"
}

function append_to_calendar() {
    filename="$1"
    if ! [ -e "$filename" ]; then
        echo "Cannot append to calendar: File does not exist"
        exit 1
    fi

    FILE_CONTENTS=$({
        awk 'BEGIN{f=1} /END:VCALENDAR/ {f=0} f' "$filename"
        cat
        awk 'BEGIN{f=0} /END:VCALENDAR/ {f=1} f' "$filename"
    })

    <<< "$FILE_CONTENTS" cat > "$filename"
}

working_path="$HOME/.calendar"

while ! [[ "$1" == "" ]]; do
    case "$1" in
        "init")
            shift
            cmd_init "$@"
            exit "$?"
            ;;
        "ls")
            shift
            cd "$working_path"
            ls "$@"
            exit "$?"
            ;;
        "rm")
            shift
            cd "$working_path"
            rm "$@"
            exit "$?"
            ;;
        "edit")
            shift
            cd "$working_path"
            nano "$@"
            exit "$?"
            ;;
        "generate")
            shift
            cmd_generate "$@"
            exit "$?"
            ;;
        "add_event")
            shift
            cmd_add_event "$@"
            exit "$?"
            ;;
        "--path"|"-p")
            shift
            working_path="$1"
            ;;
        "-h"|"--help")
            show_usage
            ;;
        *)
            echo "Unknown parameter $1"
            show_usage
            exit 1
            ;;
    esac
    shift
done

show_usage